name: Test on any push

permissions:
  contents: read

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: '/.nvmrc'
          cache: 'npm'

      - uses: actions/cache@v5
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-firefox-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test
      - run: npx playwright install-deps firefox
      - if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install firefox
      - run: npm run test:browser -- --browser.name=firefox
